services:
    SqlServerDb:
        container_name: SqlServerContainer
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - 8000:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=FIAPConn_Pass123#

    rabbitmq-server:
        image: masstransit/rabbitmq:latest
        container_name: rabbitmq-server
        ports:
            - "5672:5672" # Porta de comunicação (AMQP)
            - "15672:15672" # Porta da interface de administração do RabbitMQ
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest

    fiap.tech.auth:
        container_name: auth_latest
        image: somdesp/fiap3:auth_latest
        ports:
            - 8001:8080
        depends_on:
            - SqlServerDb

    fiap.tech.api.create:
        container_name: api_creation_latest
        image: somdesp/fiap3:api_creation_latest
        ports:
            - 8002:8080
        depends_on:
            - SqlServerDb
            - rabbitmq-server
        environment:
            ConnectionStrings__FiapConnection: "Server=SqlServerDb;Database=FIAP-Fase3;User=SA;Password=FIAPConn_Pass123#;MultipleActiveResultSets=True;Persist Security Info=False;Encrypt=False;"
            ConnectionStrings__RabbitMq: "amqp://guest:guest@rabbitmq-server:5672/"

    fiap.tech.api.update:
        container_name: api_update_latest
        image: somdesp/fiap3:api_update_latest
        ports:
            - 8003:8080
        depends_on:
            - SqlServerDb
            - rabbitmq-server
        environment:
            ConnectionStrings__FiapConnection: "Server=SqlServerDb;Database=FIAP-Fase3;User=SA;Password=FIAPConn_Pass123#;MultipleActiveResultSets=True;Persist Security Info=False;Encrypt=False;"
            ConnectionStrings__RabbitMq: "amqp://guest:guest@rabbitmq-server:5672/"

    fiap.tech.api.deletion:
        container_name: api_deletion_latest
        image: somdesp/fiap3:api_deletion_latest
        ports:
            - 8004:8080
        depends_on:
            - SqlServerDb
            - rabbitmq-server
        environment:
            ConnectionStrings__FiapConnection: "Server=SqlServerDb;Database=FIAP-Fase3;User=SA;Password=FIAPConn_Pass123#;MultipleActiveResultSets=True;Persist Security Info=False;Encrypt=False;"
            ConnectionStrings__RabbitMq: "amqp://guest:guest@rabbitmq-server:5672/"

    fiap.tech.api.consult:
        container_name: api_consult_latest
        image: somdesp/fiap3:api_consult_latest
        ports:
            - 8005:8080
        depends_on:
            - SqlServerDb
            - rabbitmq-server
        environment:
            ConnectionStrings__FiapConnection: "Server=SqlServerDb;Database=FIAP-Fase3;User=SA;Password=FIAPConn_Pass123#;MultipleActiveResultSets=True;Persist Security Info=False;Encrypt=False;"
            ConnectionStrings__RabbitMq: "amqp://guest:guest@rabbitmq-server:5672/"

    fiap.tech.work.service:
        container_name: work_service_latest
        image: somdesp/fiap3:work_service_latest
        depends_on:
            - SqlServerDb
            - rabbitmq-server
        environment:
            ConnectionStrings__FiapConnection: "Server=SqlServerDb;Database=FIAP-Fase3;User=SA;Password=FIAPConn_Pass123#;MultipleActiveResultSets=True;Persist Security Info=False;Encrypt=False;"
            ConnectionStrings__RabbitMq: "amqp://guest:guest@rabbitmq-server:5672/"
