version: '3.9'

services:
    SqlServerDb:
        container_name: SqlServerContainer
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
            - 8000:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStong_Password123#

    # fiap.tech.api:
    #     container_name: FiapAPIContainer
    #     image: ${DOCKER_REGISTRY-}fiaptechapi
    #     ports:
    #         - 8002:8081
    #     build:
    #         context: .
    #         dockerfile: FIAP.TECH.API/Dockerfile
    #     depends_on:
    #         - SqlServerDb

    fiap.tech.auth:
        container_name: auth_lasted
        image: somdesp/fiap3:auth_lasted
        # profiles: [ web ]
        ports:
            - 8003:8080
        depends_on:
            - SqlServerDb
        environment:
            - ConnectionStrings__FiapConnection=Server=SqlServerDb;Database=FIAP;User=sa;Password=myStong_Password123#;MultipleActiveResultSets=True;Persist Security Info=False;Encrypt=False;
