apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fiap-tech-auth
  namespace: fiap
  labels:
    app: fiap-tech-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fiap-tech-auth
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\anderson.satelos\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: fiap-tech-auth
    spec:
      containers:
        - image: fiaptechauth:dev
          name: auth-lasted
          ports:
            - containerPort: 8080
              name: http-web-api
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: fiap-tech-auth
  namespace: fiap
spec:
  type: LoadBalancer
  ports:
    - name: "8001"
      protocol: TCP
      port: 8001
      targetPort: 8080
  selector:
    io.kompose.service: fiap-tech-auth
