apiVersion: v1
kind: Pod
metadata:
  name: fiap-tech-auth
  # namespace: fiap
  labels:
    app: fiap-tech-auth
spec:
  containers:
    - image: somdesp/fiap3:auth_lasted
      name: fiap-tech-auth
      ports:
        - containerPort: 8080
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: fiap-tech-auth
  # namespace: fiap
spec:
  type: NodePort
  ports:      
    - port: 8080
      nodePort: 30081
  selector:
    app: fiap-tech-auth
