apiVersion: apps/v1
kind: Deployment
metadata:
  name: authapi-depl
spec:
  replicas: 5
  selector:
    matchLabels:
      app: authapi
  template:
    metadata:
      labels:
        app: authapi
    spec:
      containers:
        - name: authlasted
          image: somdesp/fiap3:auth_lasted
          ports:
            - containerPort: 8010
              name: http-web-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8010


---

apiVersion: v1
kind: Service
metadata:
  name: authapi-load-balancer-service
spec:
  selector:
    app.kubernetes.io/name: authapi
  ports:
    - name: authapi-port
      protocol: TCP
      port: 8010
      targetPort: 8010
  type: LoadBalancer              