apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\anderson.satelos\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: rabbitmq-server
  name: rabbitmq-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq-server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\anderson.satelos\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: rabbitmq-server
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: RABBITMQ_DEFAULT_USER
              value: guest
          image: masstransit/rabbitmq:latest
          name: rabbitmq-server
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
      restartPolicy: Always
