apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deletion-lasted
  # namespace: fiap
  labels:
    app: api-deletion-lasted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deletion-lasted
  template:
    metadata:
      labels:
        app: api-deletion-lasted
    spec:
      containers:
        - image: somdesp/fiap3:api_deletion_lasted
          name: api-deletion-lasted
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          env:
            - name: ConnectionStrings__FiapConnection
              valueFrom:
                secretKeyRef:
                  name: apiserver-secret
                  key: FiapConnection

            - name: ConnectionStrings__RabbitMq
              valueFrom:
                configMapKeyRef:
                  name: apiserver-configmap
                  key: RabbitMq

---
apiVersion: v1
kind: Service
metadata:
  name: api-deletion-lasted
  # namespace: fiap
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30084
  selector:
    app: api-deletion-lasted
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-deletion-lasted-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deletion-lasted
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
