apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-tech-auth
  # namespace: fiap
  labels:
    app: fiap-tech-auth
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: fiap-tech-auth
  template:
    metadata:
      labels: 
        app: fiap-tech-auth       
    spec:
      containers:
        - image: somdesp/fiap3:auth_lasted
          name: fiap-tech-auth
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: AppSettings__ConnectionStrings__FiapConnection 
              valueFrom:
                secretKeyRef:
                  name: apiserver-secret
                  key: FiapConnection

            - name: AppSettings__ConnectionStrings__RabbitMq
              valueFrom:
                configMapKeyRef:
                  name: apiserver-configmap
                  key: RabbitMq              
    
---

apiVersion: v1
kind: Service
metadata:
  name: fiap-tech-auth
  # namespace: fiap
spec:
  type: NodePort
  ports:      
    - port: 8080
      nodePort: 30081
  selector:
    app: fiap-tech-auth
