apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-service-lasted
  # namespace: fiap
  labels:
    app: work-service-lasted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work-service-lasted
  template:
    metadata:
      labels:
        app: work-service-lasted
    spec:
      containers:
        - image: somdesp/fiap3:work_service_lasted
          name: work-service-lasted
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
          ports:
            - containerPort: 5001
              protocol: TCP
          env:
            - name: ConnectionStrings__FiapConnection
              valueFrom:
                secretKeyRef:
                  name: apiserver-secret
                  key: FiapConnection

            - name: ConnectionStrings__RabbitMq
              valueFrom:
                configMapKeyRef:
                  name: apiserver-configmap
                  key: RabbitMq
---
apiVersion: v1
kind: Service
metadata:
  name: work-service-lasted
  # namespace: fiap
spec:
  type: NodePort
  ports:
    - port: 5001
      nodePort: 30091
  selector:
    app: work-service-lasted
